export interface BlockInspectorMeta {
  labelKey: string;
  descriptionKey: string;
  icon: string;
  iconSerif?: boolean;
  settingsSectionKey: string;
  typography?: boolean;
  alignment?: boolean;
  justify?: boolean;
  blockWidth?: boolean;
  spacing?: boolean;
  advanced?: boolean;
}

export const BLOCK_INSPECTOR_META: Record<string, BlockInspectorMeta> = {
  heading: {
    labelKey: 'contentStudio.blockHeading',
    descriptionKey: 'contentStudio.blockHeadingDescription',
    icon: 'H',
    iconSerif: true,
    settingsSectionKey: 'contentStudio.sectionHeadingSettings',
    typography: true,
    alignment: true,
    spacing: true,
    advanced: true,
  },
  paragraph: {
    labelKey: 'contentStudio.blockParagraph',
    descriptionKey: 'contentStudio.blockParagraphDescription',
    icon: 'P',
    settingsSectionKey: 'contentStudio.sectionParagraphSettings',
    typography: true,
    alignment: true,
    justify: true,
    blockWidth: true,
    spacing: true,
    advanced: true,
  },
  image: {
    labelKey: 'contentStudio.blockImage',
    descriptionKey: 'contentStudio.blockImageDescription',
    icon: 'Img',
    settingsSectionKey: 'contentStudio.sectionImageSettings',
    alignment: true,
    spacing: true,
    advanced: true,
  },
  gallery: {
    labelKey: 'contentStudio.blockGallery',
    descriptionKey: 'contentStudio.blockGalleryDescription',
    icon: 'gallery',
    settingsSectionKey: 'contentStudio.sectionGallerySettings',
    spacing: true,
    advanced: true,
  },
  link: {
    labelKey: 'contentStudio.blockLink',
    descriptionKey: 'contentStudio.blockLinkDescription',
    icon: 'Link',
    settingsSectionKey: 'contentStudio.sectionLinkSettings',
  },
  bulletList: {
    labelKey: 'contentStudio.blockList',
    descriptionKey: 'contentStudio.blockListDescription',
    icon: '•',
    settingsSectionKey: 'contentStudio.sectionListSettings',
    alignment: true,
    spacing: true,
    advanced: true,
  },
  orderedList: {
    labelKey: 'contentStudio.blockNumberedList',
    descriptionKey: 'contentStudio.blockListDescription',
    icon: '1.',
    settingsSectionKey: 'contentStudio.sectionListSettings',
    alignment: true,
    spacing: true,
    advanced: true,
  },
  taskList: {
    labelKey: 'contentStudio.blockChecklist',
    descriptionKey: 'contentStudio.blockChecklistDescription',
    icon: '✓',
    settingsSectionKey: 'contentStudio.sectionChecklistSettings',
    alignment: true,
    spacing: true,
    advanced: true,
  },
  blockquote: {
    labelKey: 'contentStudio.blockQuote',
    descriptionKey: 'contentStudio.blockQuoteDescription',
    icon: '“',
    iconSerif: true,
    settingsSectionKey: 'contentStudio.sectionQuoteSettings',
    typography: true,
    alignment: true,
    justify: true,
    blockWidth: true,
    spacing: true,
    advanced: true,
  },
  callout: {
    labelKey: 'contentStudio.blockCallout',
    descriptionKey: 'contentStudio.blockCalloutDescription',
    icon: '!',
    settingsSectionKey: 'contentStudio.sectionCalloutSettings',
    alignment: true,
    spacing: true,
    advanced: true,
  },
  embed: {
    labelKey: 'contentStudio.blockEmbed',
    descriptionKey: 'contentStudio.blockEmbedDescription',
    icon: 'Emb',
    settingsSectionKey: 'contentStudio.sectionEmbedSettings',
    spacing: true,
    advanced: true,
  },
  audio: {
    labelKey: 'contentStudio.blockAudio',
    descriptionKey: 'contentStudio.blockAudioDescription',
    icon: 'audio',
    settingsSectionKey: 'contentStudio.sectionAudioSettings',
    spacing: true,
    advanced: true,
  },
  file: {
    labelKey: 'contentStudio.blockFile',
    descriptionKey: 'contentStudio.blockFileDescription',
    icon: 'file',
    settingsSectionKey: 'contentStudio.sectionFileSettings',
    spacing: true,
    advanced: true,
  },
  codeBlock: {
    labelKey: 'contentStudio.blockCode',
    descriptionKey: 'contentStudio.blockCodeDescription',
    icon: '</>',
    settingsSectionKey: 'contentStudio.sectionCodeSettings',
    spacing: true,
    advanced: true,
  },
  horizontalRule: {
    labelKey: 'contentStudio.blockDivider',
    descriptionKey: 'contentStudio.blockDividerDescription',
    icon: '—',
    settingsSectionKey: 'contentStudio.sectionDividerSettings',
    spacing: true,
    advanced: true,
  },
  steps: {
    labelKey: 'contentStudio.blockSteps',
    descriptionKey: 'contentStudio.blockStepsDescription',
    icon: 'Steps',
    settingsSectionKey: 'contentStudio.sectionStepsSettings',
    spacing: true,
    advanced: true,
  },
  step: {
    labelKey: 'contentStudio.blockSteps',
    descriptionKey: 'contentStudio.blockStepDescription',
    icon: 'Step',
    settingsSectionKey: 'contentStudio.sectionStepSettings',
    spacing: true,
    advanced: true,
  },
  faq: {
    labelKey: 'contentStudio.blockFaq',
    descriptionKey: 'contentStudio.blockFaqDescription',
    icon: 'FAQ',
    settingsSectionKey: 'contentStudio.sectionFaqSettings',
    spacing: true,
    advanced: true,
  },
  faqItem: {
    labelKey: 'contentStudio.blockFaq',
    descriptionKey: 'contentStudio.blockFaqItemDescription',
    icon: 'FAQ',
    settingsSectionKey: 'contentStudio.sectionFaqItemSettings',
    spacing: true,
    advanced: true,
  },
  relatedArticles: {
    labelKey: 'contentStudio.blockRelatedArticles',
    descriptionKey: 'contentStudio.blockRelatedArticlesDescription',
    icon: 'Link',
    settingsSectionKey: 'contentStudio.sectionRelatedArticlesSettings',
    spacing: true,
    advanced: true,
  },
  timeline: {
    labelKey: 'contentStudio.blockTimeline',
    descriptionKey: 'contentStudio.blockTimelineDescription',
    icon: 'timeline',
    settingsSectionKey: 'contentStudio.sectionTimelineSettings',
    spacing: true,
    advanced: true,
  },
  timelineItem: {
    labelKey: 'contentStudio.blockTimeline',
    descriptionKey: 'contentStudio.blockTimelineItemDescription',
    icon: 'timeline',
    settingsSectionKey: 'contentStudio.sectionTimelineItemSettings',
    spacing: true,
    advanced: true,
  },
  table: {
    labelKey: 'contentStudio.blockTable',
    descriptionKey: 'contentStudio.blockTableDescription',
    icon: 'Tbl',
    settingsSectionKey: 'contentStudio.sectionTableSettings',
    spacing: true,
    advanced: true,
  },
  tabs: {
    labelKey: 'contentStudio.blockTabs',
    descriptionKey: 'contentStudio.blockTabsDescription',
    icon: 'tabs',
    settingsSectionKey: 'contentStudio.sectionTabsSettings',
    spacing: true,
    advanced: true,
  },
  tabItem: {
    labelKey: 'contentStudio.blockTabs',
    descriptionKey: 'contentStudio.blockTabItemDescription',
    icon: 'tabs',
    settingsSectionKey: 'contentStudio.sectionTabItemSettings',
    spacing: true,
    advanced: true,
  },
  columns: {
    labelKey: 'contentStudio.blockColumns',
    descriptionKey: 'contentStudio.blockColumnsDescription',
    icon: 'columns',
    settingsSectionKey: 'contentStudio.sectionColumnsSettings',
    spacing: true,
    advanced: true,
  },
  column: {
    labelKey: 'contentStudio.blockColumns',
    descriptionKey: 'contentStudio.blockColumnDescription',
    icon: 'columns',
    settingsSectionKey: 'contentStudio.sectionColumnSettings',
    spacing: true,
    advanced: true,
  },
  section: {
    labelKey: 'contentStudio.blockSection',
    descriptionKey: 'contentStudio.blockSectionDescription',
    icon: 'section',
    settingsSectionKey: 'contentStudio.sectionSectionSettings',
    spacing: true,
    advanced: true,
  },
  toc: {
    labelKey: 'contentStudio.blockToc',
    descriptionKey: 'contentStudio.blockTocDescription',
    icon: 'toc',
    settingsSectionKey: 'contentStudio.sectionTocSettings',
    spacing: true,
    advanced: true,
  },
  form: {
    labelKey: 'contentStudio.blockForm',
    descriptionKey: 'contentStudio.blockFormDescription',
    icon: 'form',
    settingsSectionKey: 'contentStudio.sectionFormSettings',
    spacing: true,
    advanced: true,
  },
  social: {
    labelKey: 'contentStudio.blockSocial',
    descriptionKey: 'contentStudio.blockSocialDescription',
    icon: 'social',
    settingsSectionKey: 'contentStudio.sectionSocialSettings',
    spacing: true,
    advanced: true,
  },
  rating: {
    labelKey: 'contentStudio.blockRating',
    descriptionKey: 'contentStudio.blockRatingDescription',
    icon: 'rating',
    settingsSectionKey: 'contentStudio.sectionRatingSettings',
    spacing: true,
    advanced: true,
  },
  progress: {
    labelKey: 'contentStudio.blockProgress',
    descriptionKey: 'contentStudio.blockProgressDescription',
    icon: 'progress',
    settingsSectionKey: 'contentStudio.sectionProgressSettings',
    spacing: true,
    advanced: true,
  },
  hero: {
    labelKey: 'contentStudio.blockHero',
    descriptionKey: 'contentStudio.blockHeroDescription',
    icon: 'section',
    settingsSectionKey: 'contentStudio.sectionHeroSettings',
    spacing: true,
    advanced: true,
  },
  newsletterSignup: {
    labelKey: 'contentStudio.blockNewsletter',
    descriptionKey: 'contentStudio.blockNewsletterDescription',
    icon: 'form',
    settingsSectionKey: 'contentStudio.sectionNewsletterSettings',
    spacing: true,
    advanced: true,
  },
};

export const FONT_SIZE_OPTIONS = [
  { value: '0.875rem', labelKey: 'contentStudio.fontSizeSmall' },
  { value: '1rem', labelKey: 'contentStudio.fontSizeBase' },
  { value: '1.125rem', labelKey: 'contentStudio.fontSizeMedium' },
  { value: '1.25rem', labelKey: 'contentStudio.fontSizeLarge' },
  { value: '1.5rem', labelKey: 'contentStudio.fontSizeXLarge' },
  { value: '1.875rem', labelKey: 'contentStudio.fontSize2XLarge' },
  { value: '2.25rem', labelKey: 'contentStudio.fontSize3XLarge' },
  { value: '2.5rem', labelKey: 'contentStudio.fontSize4XLarge' },
] as const;

export const LINE_HEIGHT_OPTIONS = [
  { value: '1.25', labelKey: 'contentStudio.lineHeightTight' },
  { value: '1.375', labelKey: 'contentStudio.lineHeightSnug' },
  { value: '1.5', labelKey: 'contentStudio.lineHeightNormal' },
  { value: '1.625', labelKey: 'contentStudio.lineHeightRelaxed' },
  { value: '1.75', labelKey: 'contentStudio.lineHeightLoose' },
  { value: '2', labelKey: 'contentStudio.lineHeightDouble' },
] as const;

export const DEFAULT_TEXT_COLOR = '#111827';
