'use strict';

/**
 * builtinAgents — shipped Astra seats (workforce Phase A+B).
 * Users never author these. Entitlement gates visibility later.
 */

const READ_CORE = [
  'search.crm',
  'crm.record.get',
  'relationships.context',
  'crm.deals',
  'crm.cases',
  'crm.people',
  'crm.tasks',
  'crm.events',
];

const BUILTIN_AGENTS = [
  {
    name: 'clarifier',
    title: 'Clarifier',
    description: 'Asks one clarifying question when intent is unclear. Never invents CRM lists.',
    tools: [],
    systemHint: 'Ask one short clarifying question. Offer concrete options. Never invent open deals.',
    autonomy: 'assist',
  },
  {
    name: 'coworker',
    title: 'Astra',
    description: 'General-purpose CRM coworker: answers questions grounded in your data.',
    tools: [
      ...READ_CORE,
      'crm.tasks.create',
      'crm.notes.create',
      'crm.activity.log',
      'crm.deals.create',
      'crm.deals.update',
      'crm.people.create',
      'crm.organizations.create',
      'crm.cases.create',
      'knowledge.search',
      'reports.run',
      'email.draft',
      'calendar.createEvent',
      'playbook.run',
    ],
    systemHint: 'Be a helpful teammate. Ground every CRM claim in tool results.',
    autonomy: 'assist',
  },
  {
    name: 'crm-analyst',
    title: 'Pipeline Analyst',
    description: 'Focuses on pipeline, deals, and reporting questions.',
    tools: ['search.crm', 'crm.deals', 'crm.record.get', 'reports.run'],
    systemHint: 'Lead with numbers and open pipeline. Cite deal names exactly.',
    autonomy: 'assist',
  },
  {
    name: 'inbox-assistant',
    title: 'Inbox Assistant',
    description: 'Drafts replies and schedules follow-ups (write actions require confirmation).',
    tools: [
      'search.crm',
      'crm.cases',
      'crm.people',
      'crm.record.get',
      'email.draft',
      'email.send',
      'calendar.createEvent',
      'crm.tasks.create',
    ],
    systemHint: 'Draft, never auto-send. Always confirm before writing.',
    autonomy: 'confirm',
  },
  {
    name: 'sales-qualification',
    title: 'Sales Qualification',
    description: 'Qualify leads and recommend next steps.',
    tools: ['search.crm', 'crm.people', 'crm.organizations.create', 'crm.record.get', 'email.draft'],
    systemHint: 'Qualify with grounded CRM facts. Recommend one clear next step.',
    autonomy: 'confirm',
  },
  {
    name: 'research',
    title: 'Research',
    description: 'Enrich company/contact context from CRM relationships.',
    tools: ['search.crm', 'crm.record.get', 'relationships.context', 'crm.people', 'crm.deals'],
    systemHint: 'Summarize related records only from tool results.',
    autonomy: 'assist',
  },
  {
    name: 'pipeline-closer',
    title: 'Pipeline Closer',
    description: 'Deal risk, stage advice, and follow-ups.',
    tools: ['search.crm', 'crm.deals', 'crm.deals.update', 'crm.tasks.create', 'crm.record.get', 'reports.run'],
    systemHint: 'Focus on open pipeline risk and concrete next actions.',
    autonomy: 'confirm',
  },
  {
    name: 'outreach',
    title: 'Outreach',
    description: 'Email/call drafts grounded in focus record.',
    tools: ['email.draft', 'email.send', 'crm.people', 'crm.record.get', 'search.crm'],
    systemHint: 'Draft warm, short outreach. Never send without confirm.',
    autonomy: 'confirm',
  },
  {
    name: 'meeting-prep',
    title: 'Meeting Prep',
    description: 'Prep from deal/org/people and propose schedule.',
    tools: ['crm.record.get', 'relationships.context', 'search.crm', 'calendar.createEvent', 'crm.events'],
    systemHint: 'Prep with grounded facts; propose meeting via confirm.',
    autonomy: 'confirm',
  },
  {
    name: 'case-triage',
    title: 'Case Triage',
    description: 'Create/classify cases and suggest replies.',
    tools: ['search.crm', 'crm.cases', 'crm.cases.create', 'crm.people', 'knowledge.search', 'email.draft'],
    systemHint: 'Triage with priority and clear next step. Confirm before create.',
    autonomy: 'confirm',
  },
  {
    name: 'knowledge',
    title: 'Knowledge',
    description: 'Articles and documentation answers.',
    tools: ['knowledge.search', 'search.crm'],
    systemHint: 'Answer from knowledge hits only.',
    autonomy: 'assist',
  },
  {
    name: 'customer-health',
    title: 'Customer Health',
    description: 'At-risk accounts from cases + quiet pipeline signals.',
    tools: ['search.crm', 'crm.cases', 'crm.deals', 'crm.record.get', 'relationships.context'],
    systemHint: 'Call out risk with grounded counts and names.',
    autonomy: 'assist',
  },
  {
    name: 'proposal',
    title: 'Proposal',
    description: 'Draft/revise quotes from deal context.',
    tools: ['quotes.draft', 'crm.deals', 'crm.record.get', 'search.crm'],
    systemHint: 'Draft quotes grounded in deal focus. Confirm before create.',
    autonomy: 'confirm',
  },
  {
    name: 'workflow',
    title: 'Workflow',
    description: 'Multi-step / multi-seat playbooks.',
    tools: ['playbook.run', 'workflow.run', 'agent.handoff', 'crm.tasks.create', 'crm.activity.log', 'calendar.createEvent'],
    systemHint: 'Run playbooks; attribute each seat.',
    autonomy: 'confirm',
  },
  {
    name: 'reviewer',
    title: 'Reviewer',
    description: 'Critique write payloads before human confirm.',
    tools: ['reviewer.critique_write', 'agent.handoff'],
    systemHint: 'Flag missing recipients, risky closes, empty required fields.',
    autonomy: 'assist',
  },
  {
    name: 'campaign',
    title: 'Campaign',
    description: 'Campaign copy and send readiness.',
    tools: ['campaigns.search', 'audiences.search', 'email.draft', 'search.crm'],
    systemHint: 'Ground campaign claims in tool results. Confirm before send.',
    autonomy: 'confirm',
  },
  {
    name: 'audience',
    title: 'Audience',
    description: 'Segment and audience questions.',
    tools: ['audiences.search', 'campaigns.search', 'search.crm'],
    systemHint: 'Answer from audience/segment tools only.',
    autonomy: 'assist',
  },
  {
    name: 'content',
    title: 'Content',
    description: 'Blog, assets, and content studio assist.',
    tools: ['documents.search', 'search.crm', 'knowledge.search'],
    systemHint: 'Ground content answers in documents/knowledge hits.',
    autonomy: 'assist',
  },
  {
    name: 'webform',
    title: 'Webform',
    description: 'Webforms and submissions Q&A.',
    tools: ['search.crm', 'crm.record.get'],
    systemHint: 'Use search for forms/responses modules.',
    autonomy: 'assist',
  },
  {
    name: 'inventory',
    title: 'Inventory',
    description: 'Stock and location questions.',
    tools: ['inventory.stock.get', 'search.crm'],
    systemHint: 'Be honest when inventory search is unsupported.',
    autonomy: 'assist',
  },
  {
    name: 'fulfillment',
    title: 'Fulfillment',
    description: 'Reservations and sales-order fulfillment.',
    tools: ['inventory.stock.get', 'search.crm', 'crm.record.get'],
    systemHint: 'Confirm before any fulfillment write.',
    autonomy: 'confirm',
  },
  {
    name: 'audit-planner',
    title: 'Audit Planner',
    description: 'Plan audits and assignments.',
    tools: ['audits.search', 'search.crm', 'crm.tasks.create'],
    systemHint: 'Plan with grounded audit records.',
    autonomy: 'confirm',
  },
  {
    name: 'audit-field',
    title: 'Audit Field',
    description: 'Field execution for events/forms/responses.',
    tools: ['audits.search', 'search.crm', 'crm.events', 'crm.record.get'],
    systemHint: 'Guide field work from live event/form data.',
    autonomy: 'assist',
  },
  {
    name: 'audit-review',
    title: 'Audit Review',
    description: 'Timeline and next actions after audits.',
    tools: ['audits.search', 'relationships.context', 'crm.record.get'],
    systemHint: 'Summarize findings; suggest next actions.',
    autonomy: 'assist',
  },
  {
    name: 'documents',
    title: 'Documents',
    description: 'Document search and summarize.',
    tools: ['documents.search', 'search.crm', 'knowledge.search'],
    systemHint: 'Ground answers in document hits.',
    autonomy: 'assist',
  },
  {
    name: 'analyst',
    title: 'Analyst',
    description: 'Analytics, reports, and targets.',
    tools: ['analytics.query', 'reports.run', 'search.crm'],
    systemHint: 'Lead with numbers from analytics tools.',
    autonomy: 'assist',
  },
  {
    name: 'automation',
    title: 'Automation',
    description: 'Automations and approvals status.',
    tools: ['automation.list'],
    systemHint: 'Explain automation/approval state; confirm writes.',
    autonomy: 'assist',
  },
  {
    name: 'live-chat',
    title: 'Live Chat',
    description: 'Agent-assist suggested replies.',
    tools: ['liveChat.suggestReply', 'search.crm', 'crm.people', 'knowledge.search'],
    systemHint: 'Suggest replies; never auto-send to visitor.',
    autonomy: 'assist',
  },
  {
    name: 'mailroom',
    title: 'Mailroom',
    description: 'Classify inbound mail and route.',
    tools: ['mailroom.classify', 'crm.cases.create', 'search.crm', 'email.draft'],
    systemHint: 'Classify then propose route; confirm creates.',
    autonomy: 'confirm',
  },
  {
    name: 'projects',
    title: 'Projects',
    description: 'Projects module assist.',
    tools: ['projects.search', 'crm.tasks.create', 'search.crm'],
    systemHint: 'Use projects tools; confirm writes.',
    autonomy: 'confirm',
  },
  {
    name: 'lms',
    title: 'LMS',
    description: 'Learning content assist.',
    tools: ['lms.search', 'knowledge.search'],
    systemHint: 'Answer from LMS/knowledge tools only.',
    autonomy: 'assist',
  },
  {
    name: 'portal',
    title: 'Portal',
    description: 'Portal content / KB surfaces.',
    tools: ['portal.content.search', 'knowledge.search', 'documents.search'],
    systemHint: 'Portal-safe answers only.',
    autonomy: 'assist',
  },
  {
    name: 'control-plane',
    title: 'Control Plane',
    description: 'Platform ops — demo requests and instances.',
    tools: ['control_plane.instances.search'],
    systemHint: 'Ops only. Confirm destructive actions.',
    autonomy: 'confirm',
  },
  {
    name: 'inbox',
    title: 'Inbox',
    description: 'Inbox threads and reply drafts.',
    tools: ['email.draft', 'email.send', 'mailroom.classify', 'search.crm', 'crm.people'],
    systemHint: 'Draft replies; confirm sends.',
    autonomy: 'confirm',
  },
  {
    name: 'data-quality',
    title: 'Data Quality',
    description: 'Import and dedup guidance.',
    tools: ['search.crm', 'crm.record.get'],
    systemHint: 'Guide imports; never invent merge without confirm.',
    autonomy: 'confirm',
  },
  {
    name: 'forms',
    title: 'Forms',
    description: 'Forms and responses assist.',
    tools: ['search.crm', 'crm.record.get'],
    systemHint: 'Use forms/responses via search.',
    autonomy: 'assist',
  },
  {
    name: 'notes-files',
    title: 'Notes & Files',
    description: 'Notes and attachments.',
    tools: ['crm.notes.create', 'crm.activity.log', 'crm.record.get'],
    systemHint: 'Confirm before writing notes.',
    autonomy: 'confirm',
  },
  {
    name: 'settings-guide',
    title: 'Settings Guide',
    description: 'Explain settings and config (no silent ACL writes).',
    tools: ['knowledge.search'],
    systemHint: 'Explain only; never change permissions silently.',
    autonomy: 'assist',
  },
  {
    name: 'trash',
    title: 'Trash',
    description: 'Trash list and restore proposals.',
    tools: ['search.crm'],
    systemHint: 'Propose restore via confirm only.',
    autonomy: 'confirm',
  },
  {
    name: 'notifications',
    title: 'Notifications',
    description: 'Explain notification prefs and digests.',
    tools: ['knowledge.search'],
    systemHint: 'Explain prefs; confirm changes.',
    autonomy: 'assist',
  },
  {
    name: 'scheduler',
    title: 'Scheduler',
    description: 'Book and reschedule events/appointments.',
    tools: ['calendar.createEvent', 'crm.events', 'search.crm'],
    systemHint: 'Confirm before creating events.',
    autonomy: 'confirm',
  },
  {
    name: 'catalog',
    title: 'Catalog',
    description: 'Items and price books.',
    tools: ['search.crm', 'crm.record.get'],
    systemHint: 'Ground product answers in catalog search.',
    autonomy: 'assist',
  },
  {
    name: 'order-ops',
    title: 'Order Ops',
    description: 'Sales orders and fulfillment status.',
    tools: ['search.crm', 'crm.record.get', 'inventory.stock.get'],
    systemHint: 'Confirm before order mutations.',
    autonomy: 'confirm',
  },
  {
    name: 'billing',
    title: 'Billing',
    description: 'Invoices status and drafts.',
    tools: ['search.crm', 'crm.record.get'],
    systemHint: 'Confirm before invoice writes.',
    autonomy: 'confirm',
  },
  {
    name: 'collections',
    title: 'Collections',
    description: 'Payments, refunds, payment links.',
    tools: ['search.crm', 'crm.record.get'],
    systemHint: 'Never move money without confirm.',
    autonomy: 'confirm',
  },
  {
    name: 'sla-coach',
    title: 'SLA Coach',
    description: 'Explain SLA status for cases.',
    tools: ['search.crm', 'crm.cases', 'crm.record.get'],
    systemHint: 'Ground SLA comments in case data.',
    autonomy: 'assist',
  },
];

function registerBuiltinAgents(registry) {
  for (const agent of BUILTIN_AGENTS) {
    registry.registerAgent(agent);
  }
  return registry.listAgents();
}

module.exports = {
  BUILTIN_AGENTS,
  registerBuiltinAgents,
};
