import {
  ArrowsUpDownIcon,
  Bars3BottomLeftIcon,
  BuildingOffice2Icon,
  CalculatorIcon,
  CodeBracketIcon,
  CursorArrowRaysIcon,
  DocumentDuplicateIcon,
  DocumentTextIcon,
  HashtagIcon,
  LinkIcon,
  ListBulletIcon,
  MapPinIcon,
  MinusIcon,
  PhotoIcon,
  QrCodeIcon,
  QueueListIcon,
  RectangleStackIcon,
  ShareIcon,
  TableCellsIcon,
  UserCircleIcon,
  VariableIcon,
  ViewColumnsIcon,
  ArrowsRightLeftIcon,
  BanknotesIcon,
  PencilSquareIcon,
  DocumentIcon,
  ArrowPathIcon,
  CommandLineIcon
} from '@heroicons/vue/24/outline';

/** @type {Record<string, import('vue').Component>} */
export const BUILDER_COMPONENT_ICONS = {
  Page: DocumentIcon,
  Section: RectangleStackIcon,
  Container: RectangleStackIcon,
  Row: ViewColumnsIcon,
  Column: QueueListIcon,
  Divider: MinusIcon,
  Spacer: ArrowsUpDownIcon,
  PageBreak: DocumentDuplicateIcon,
  Heading: Bars3BottomLeftIcon,
  Paragraph: DocumentTextIcon,
  RichText: DocumentTextIcon,
  List: ListBulletIcon,
  Link: LinkIcon,
  Image: PhotoIcon,
  Logo: PhotoIcon,
  Icon: HashtagIcon,
  QrCode: QrCodeIcon,
  Barcode: QrCodeIcon,
  Signature: PencilSquareIcon,
  MergeTag: CodeBracketIcon,
  Variable: VariableIcon,
  Formula: CalculatorIcon,
  Table: TableCellsIcon,
  Repeater: ArrowPathIcon,
  LineItem: ListBulletIcon,
  RelatedRecords: ArrowsRightLeftIcon,
  Totals: BanknotesIcon,
  TaxSummary: CalculatorIcon,
  AddressBlock: MapPinIcon,
  ContactCard: UserCircleIcon,
  OrganizationBlock: BuildingOffice2Icon,
  Button: CursorArrowRaysIcon,
  SocialIcons: ShareIcon,
  Header: DocumentIcon,
  Footer: DocumentIcon,
  PageNumber: HashtagIcon,
  Watermark: DocumentTextIcon,
  ConditionalBlock: CommandLineIcon,
  Loop: ArrowPathIcon,
  Html: CodeBracketIcon
};

export function resolveBuilderIcon(type) {
  return BUILDER_COMPONENT_ICONS[String(type || '')] || DocumentTextIcon;
}
