apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.instance.name }}-backend
  namespace: {{ .Values.instance.name }}
  labels:
    app: litedesk-backend
    instance: {{ .Values.instance.subdomain }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: litedesk-backend
      instance: {{ .Values.instance.subdomain }}
  template:
    metadata:
      labels:
        app: litedesk-backend
        instance: {{ .Values.instance.subdomain }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.backend.env.port }}
          protocol: TCP
        env:
        - name: NODE_ENV
          value: {{ .Values.backend.env.nodeEnv }}
        - name: PORT
          value: "{{ .Values.backend.env.port }}"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Values.instance.name }}-mongodb-secret
              key: connection-string
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.instance.name }}-app-secret
              key: jwt-secret
        - name: JWT_EXPIRES_IN
          value: {{ .Values.backend.env.jwtExpiresIn }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}

