apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.instance.name }}-frontend
  namespace: {{ .Values.instance.name }}
  labels:
    app: litedesk-frontend
    instance: {{ .Values.instance.subdomain }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: litedesk-frontend
      instance: {{ .Values.instance.subdomain }}
  template:
    metadata:
      labels:
        app: litedesk-frontend
        instance: {{ .Values.instance.subdomain }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.frontend.targetPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}

