---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.instance.name }}-app-secret
  namespace: {{ .Values.instance.name }}
type: Opaque
stringData:
  jwt-secret: {{ randAlphaNum 32 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.instance.name }}-mongodb-secret
  namespace: {{ .Values.instance.name }}
type: Opaque
stringData:
  mongodb-root-password: {{ randAlphaNum 24 | quote }}
  mongodb-password: {{ randAlphaNum 24 | quote }}
  connection-string: "mongodb://{{ .Values.mongodb.auth.username }}:PASSWORD_PLACEHOLDER@{{ .Values.instance.name }}-mongodb:27017/{{ .Values.mongodb.auth.database }}"

