<!--
  Meeting record hero: join conference / show mode — not field-sales "Start Event" execution.
-->
<template>
  <div
    class="rounded-2xl border border-sky-200/70 bg-gradient-to-br from-sky-50/90 to-white p-5 shadow-sm dark:border-sky-500/25 dark:from-sky-950/35 dark:to-gray-900"
  >
    <div class="flex flex-wrap items-start justify-between gap-3">
      <div class="min-w-0">
        <p class="text-xs font-semibold uppercase tracking-wider text-sky-700 dark:text-sky-300">
          {{ t('events.meetingRecordBadge') }}
        </p>
        <p class="mt-1 text-sm text-gray-700 dark:text-gray-300">
          {{ headline }}
        </p>
        <p v-if="scheduleLine" class="mt-1 text-xs text-gray-500 dark:text-gray-400">
          {{ scheduleLine }}
        </p>
      </div>
      <BadgeCell
        v-if="statusLabel"
        :value="statusLabel"
        :variant-map="statusVariantMap"
      />
    </div>

    <dl class="mt-4 grid gap-3 sm:grid-cols-2">
      <div v-if="modeLabel">
        <dt class="text-xs font-medium text-gray-500 dark:text-gray-400">
          {{ t('events.sysFieldMeetingMode') }}
        </dt>
        <dd class="mt-0.5 text-sm font-medium text-gray-900 dark:text-white">
          {{ modeLabel }}
        </dd>
      </div>
      <div v-if="providerLabel && isOnlineMode">
        <dt class="text-xs font-medium text-gray-500 dark:text-gray-400">
          {{ t('events.sysFieldConferenceProvider') }}
        </dt>
        <dd class="mt-0.5 text-sm font-medium text-gray-900 dark:text-white">
          {{ providerLabel }}
        </dd>
      </div>
      <div v-if="showLocation && locationText" class="sm:col-span-2">
        <dt class="text-xs font-medium text-gray-500 dark:text-gray-400">
          {{ t('events.sysFieldLocation') }}
        </dt>
        <dd class="mt-0.5 text-sm font-medium text-gray-900 dark:text-white">
          {{ locationText }}
        </dd>
      </div>
    </dl>

    <div class="mt-4 flex flex-wrap items-center gap-2">
      <a
        v-if="joinHref"
        :href="joinHref"
        target="_blank"
        rel="noopener noreferrer"
        class="inline-flex items-center gap-2 rounded-xl bg-sky-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-sky-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-gray-900"
      >
        <VideoCameraIcon class="h-4 w-4 shrink-0" aria-hidden="true" />
        {{ joinLabel }}
      </a>
      <button
        v-if="joinHref"
        type="button"
        class="inline-flex items-center gap-1.5 rounded-xl border border-sky-200 bg-white px-3 py-2 text-sm font-medium text-sky-800 hover:bg-sky-50 dark:border-sky-500/40 dark:bg-gray-900 dark:text-sky-200 dark:hover:bg-sky-950/40"
        @click="copyJoinLink"
      >
        <ClipboardDocumentIcon class="h-4 w-4 shrink-0" aria-hidden="true" />
        {{ copyDone ? t('events.meetingRecordLinkCopied') : t('events.meetingRecordCopyLink') }}
      </button>
      <p
        v-else-if="isOnlineMode"
        class="text-sm text-amber-800 dark:text-amber-200"
      >
        {{ t('events.meetingRecordNoJoinLink') }}
      </p>
      <p
        v-else-if="isInPerson"
        class="text-sm text-gray-600 dark:text-gray-400"
      >
        {{ t('events.meetingRecordInPersonHint') }}
      </p>
    </div>

    <p
      v-if="autoGenerated"
      class="mt-3 text-xs text-sky-700 dark:text-sky-300"
    >
      {{ t('events.meetingRecordLinkAutoGenerated') }}
    </p>

    <div v-if="participantNames.length" class="mt-4 border-t border-sky-100 pt-3 dark:border-sky-500/20">
      <p class="text-xs font-medium text-gray-500 dark:text-gray-400">
        {{ t('events.sysFieldAttendees') }}
      </p>
      <p class="mt-1 text-sm text-gray-800 dark:text-gray-200">
        {{ participantNames.join(', ') }}
      </p>
    </div>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { VideoCameraIcon, ClipboardDocumentIcon } from '@heroicons/vue/24/outline';
import BadgeCell from '@/components/common/table/BadgeCell.vue';
import {
  MEETING_CONFERENCE_PROVIDERS,
  isValidMeetingConferenceProvider
} from '@/constants/meetingConferenceProviders';

const props = defineProps({
  event: { type: Object, required: true }
});

const { t, d } = useI18n();
const copyDone = ref(false);
let copyResetTimer = null;

async function copyJoinLink() {
  const href = joinHref.value;
  if (!href) return;
  try {
    await navigator.clipboard.writeText(href);
    copyDone.value = true;
    if (copyResetTimer) clearTimeout(copyResetTimer);
    copyResetTimer = setTimeout(() => {
      copyDone.value = false;
    }, 2000);
  } catch {
    /* ignore */
  }
}

const participantNames = computed(() => {
  const list = props.event?.attendees;
  if (!Array.isArray(list)) return [];
  return list
    .map((u) => {
      if (!u || typeof u !== 'object') return '';
      const name = [u.firstName, u.lastName].filter(Boolean).join(' ').trim();
      return name || u.email || '';
    })
    .filter(Boolean);
});

const statusVariantMap = {
  planned: 'info',
  scheduled: 'info',
  completed: 'success',
  cancelled: 'danger',
  canceled: 'danger'
};

const statusLabel = computed(() => String(props.event?.status || '').trim() || null);

const mode = computed(() => String(props.event?.meetingMode || '').trim());
const isVirtual = computed(() => mode.value === 'Virtual');
const isHybrid = computed(() => mode.value === 'Hybrid');
const isInPerson = computed(() => mode.value === 'In-person');
const isOnlineMode = computed(() => isVirtual.value || isHybrid.value);

const modeLabel = computed(() => {
  if (!mode.value) return null;
  return mode.value;
});

const provider = computed(() => {
  const raw = props.event?.conferenceProvider;
  return isValidMeetingConferenceProvider(raw) ? raw : null;
});

const providerLabel = computed(() => {
  if (!provider.value) return null;
  const def = MEETING_CONFERENCE_PROVIDERS.find((p) => p.value === provider.value);
  return def ? t(def.labelKey) : provider.value;
});

const joinRaw = computed(() => {
  const link =
    props.event?.meetingLink ||
    props.event?.appointment?.meetingLink ||
    '';
  return typeof link === 'string' ? link.trim() : '';
});

const autoGenerated = computed(
  () => !!props.event?.appointment?.meetingLinkAutoGenerated
);

const joinHref = computed(() => {
  const raw = joinRaw.value;
  if (!raw) return null;
  if (/^https?:\/\//i.test(raw)) return raw;
  if (/^[\w.-]+\.[a-z]{2,}/i.test(raw)) return `https://${raw}`;
  return raw;
});

const joinLabel = computed(() => {
  if (provider.value === 'google_meet') return t('events.meetingRecordJoinGoogleMeet');
  if (provider.value === 'ms_teams') return t('events.meetingRecordJoinMsTeams');
  if (provider.value === 'zoom') return t('events.meetingRecordJoinZoom');
  return t('events.meetingRecordJoinMeeting');
});

const locationText = computed(() => {
  const loc = props.event?.location || props.event?.geoLocation?.address || '';
  return typeof loc === 'string' ? loc.trim() : '';
});

const showLocation = computed(() => isInPerson.value || isHybrid.value);

const headline = computed(() => {
  if (isVirtual.value && providerLabel.value) {
    return t('events.meetingRecordHeadlineVirtual', { provider: providerLabel.value });
  }
  if (isHybrid.value && providerLabel.value) {
    return t('events.meetingRecordHeadlineHybrid', { provider: providerLabel.value });
  }
  if (isInPerson.value) {
    return t('events.meetingRecordHeadlineInPerson');
  }
  return t('events.meetingRecordHeadlineDefault');
});

const scheduleLine = computed(() => {
  const start = props.event?.startDateTime;
  const end = props.event?.endDateTime;
  if (!start) return null;
  try {
    const startDate = new Date(start);
    if (Number.isNaN(startDate.getTime())) return null;
    const startStr = d(startDate, {
      dateStyle: 'medium',
      timeStyle: 'short'
    });
    if (!end) return startStr;
    const endDate = new Date(end);
    if (Number.isNaN(endDate.getTime())) return startStr;
    const endStr = d(endDate, { timeStyle: 'short' });
    return `${startStr} – ${endStr}`;
  } catch {
    return null;
  }
});
</script>
