/**
 * Localized titles/actions for record page section stacks (records.* namespace).
 * @param {(key: string) => string} t
 */
export function createRecordSectionLabels(t) {
  return {
    description: t('records.descriptionTitle'),
    lines: t('records.linesTitle'),
    dealLines: t('records.dealLinesSectionTitle'),
    revisions: t('records.revisionsTitle'),
    conversion: t('records.conversionTitle'),
    source: t('records.salesOrderSourceTitle'),
    fulfillment: t('records.salesOrderFulfillmentTitle'),
    lineage: t('records.salesOrderLineageTitle'),
    billing: t('records.salesOrderBillingCoverageTitle'),
    invoice: t('records.salesOrderInvoiceTitle'),
    credits: t('records.invoiceCreditNotesTitle'),
    catalog: t('records.catalogSectionTitle'),
    vendorCatalog: t('organizations.vendorCatalogTitle'),
    file: t('documents.fileSectionTitle'),
    content: t('documents.editorSectionTitle'),
    openEditor: t('documents.openEditor'),
    visibility: t('documents.visibilityTitle'),
    presence: t('documents.presenceSectionTitle'),
    reservation: t('documents.reservationSectionTitle'),
    lifecycle: t('documents.lifecycleTitle'),
    comments: t('documents.commentsSectionTitle'),
    signatures: t('documents.signaturesSectionTitle'),
    collaboration: t('documents.collaborationSectionTitle'),
    details: t('records.detailsTitle'),
    preview: t('records.tabPreview'),
    responses: t('records.tabResponses'),
    related: t('records.relatedRecordsTitle'),
    stageHistory: t('records.stageHistoryTitle'),
    stagePlaybook: t('records.stagePlaybookTitle'),
    subtasks: t('records.subtasksTitle'),
    subtasksWithCount: (completed, total) =>
      t('records.subtasksTitleWithCount', { completed, total }),
    expand: t('records.sectionExpand'),
    history: t('records.sectionHistory'),
    linkRecord: t('records.sectionLinkRecord'),
    addRecord: t('records.sectionAddRecord'),
    addSubtask: t('records.sectionAddSubtask'),
    viewMore: t('records.sectionViewMore'),
    viewLess: t('records.sectionViewLess'),
    viewAll: (count) => t('records.sectionViewAll', { count }),
    groupCore: t('records.sectionGroupCore'),
    groupSystem: t('records.sectionGroupSystem'),
    groupOther: t('records.sectionGroupOther'),
    createdVia: t('records.sectionCreatedVia'),
    groupRecord: t('records.sectionGroupRecord'),
  };
}
