'use strict';

/**
 * Full Tally XML / Fetch field catalogs per connector entityType.
 * Sourced from docs/TALLY_VERIFIED_FIELD_SCHEMA.md + Sample XML + GST Rel 3 / e-Invoice tags.
 * Only real / partial Tally tags — no Arivu sync-meta invent fields.
 */

const TALLY_FIELD_CATALOGS = Object.freeze({
  party: [
    'NAME',
    'PARENT',
    'GUID',
    'MASTERID',
    'ALTERID',
    'REMOTEALTERID',
    'MAILINGNAME',
    'ADDRESS',
    'LEDGERPHONE',
    'LEDGERMOBILE',
    'LEDGERCONTACT',
    'EMAIL',
    'WEBSITE',
    'PINCODE',
    'COUNTRY',
    'COUNTRYNAME',
    'LEDGERSTATENAME',
    'STATECODE',
    'PARTYGSTIN',
    'GSTIN',
    'GSTREGISTRATIONTYPE',
    'GSTAPPLICABLE',
    'GSTDUTYHEAD',
    'GSTTYPEOFSUPPLY',
    'GSTAPPROPRIATETO',
    'PLACEOFSUPPLY',
    'INCOMETAXNUMBER',
    'CREDITLIMIT',
    'BILLCREDITPERIOD',
    'OPENINGBALANCE',
    'CLOSINGBALANCE',
    'ISBILLWISEON',
    'ISCOSTCENTRESON',
    'CURRENCYNAME',
    'NARRATION',
    'TAXTYPE',
    'ISBEHAVEASDUTY',
    'BANKNAME',
    'ACCOUNTNUMBER',
    'IFSCODE',
  ],
  group: [
    'NAME',
    'PARENT',
    'GUID',
    'MASTERID',
    'ALTERID',
    'ISREVENUE',
    'ISDEEMEDPOSITIVE',
    'ISADDABLE',
    'ISCOSTCENTRESON',
    'GSTAPPLICABLE',
  ],
  item: [
    'NAME',
    'PARENT',
    'GUID',
    'MASTERID',
    'ALTERID',
    'REMOTEALTERID',
    'BASEUNITS',
    'ADDITIONALUNITS',
    'CONVERSION',
    'DESCRIPTION',
    'PARTNO',
    'MAILINGNAME',
    'NARRATION',
    'CATEGORY',
    'COSTINGMETHOD',
    'VALUATIONMETHOD',
    'HASBATCHNUMBERS',
    'ISBATCHWISEON',
    'HASEXPIRYDATE',
    'ISPERISHABLE',
    'OPENINGBALANCE',
    'CLOSINGBALANCE',
    'OPENINGRATE',
    'CLOSINGRATE',
    'OPENINGVALUE',
    'CLOSINGVALUE',
    'GODOWNNAME',
    'HSNCODE',
    'HSN',
    'GSTRATE',
    'GSTAPPLICABLE',
    'GSTTYPEOFSUPPLY',
    'RATE',
    'STANDARDPRICELIST',
    'STANDARDCOSTLIST',
    'BARCODE',
    'MRP',
    'IGNOREPHYSICALDIFFERENCE',
    'IGNORENEGATIVESTOCK',
  ],
  godown: [
    'NAME',
    'PARENT',
    'GUID',
    'MASTERID',
    'ALTERID',
    'ADDRESS',
    'GODOWNTYPE',
    'HASSTOCK',
    'JOBBERSTOCK',
  ],
  stock_group: ['NAME', 'PARENT', 'GUID', 'MASTERID', 'ALTERID', 'ISADDABLE', 'GSTAPPLICABLE', 'HSNCODE'],
  stock_category: ['NAME', 'PARENT', 'GUID', 'MASTERID', 'ALTERID'],
  tax_ledger: [
    'NAME',
    'PARENT',
    'GUID',
    'MASTERID',
    'ALTERID',
    'TAXTYPE',
    'GSTDUTYHEAD',
    'ISBEHAVEASDUTY',
    'GSTAPPLICABLE',
    'GSTRATE',
  ],
  invoice: [
    'DATE',
    'EFFECTIVEDATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'PARTYLEDGERNAME',
    'BASICBUYERNAME',
    'PARTYGSTIN',
    'PLACEOFSUPPLY',
    'GSTREGISTRATIONTYPE',
    'GSTREGISTRATION',
    'AMOUNT',
    'IRN',
    'IRNACKNO',
    'IRNACKDATE',
    'IRNQRCODE',
    'BILLTOPLACE',
    'SHIPTOPLACE',
    'CONSIGNEEGSTIN',
    'CONSIGNEESTATENAME',
    'ISCANCELLED',
    'ISOPTIONAL',
    'ISINVOICE',
    'ENTEREDBY',
    'STOCKITEMNAME',
    'ACTUALQTY',
    'BILLEDQTY',
    'RATE',
    'GODOWNNAME',
    'BATCHNAME',
    'LEDGERNAME',
  ],
  purchase: [
    'DATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'PARTYLEDGERNAME',
    'PARTYGSTIN',
    'PLACEOFSUPPLY',
    'AMOUNT',
    'ISCANCELLED',
    'STOCKITEMNAME',
    'ACTUALQTY',
    'BILLEDQTY',
    'RATE',
    'GODOWNNAME',
    'LEDGERNAME',
  ],
  payment: [
    'DATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'PARTYLEDGERNAME',
    'AMOUNT',
    'LEDGERNAME',
    'ISCANCELLED',
  ],
  receipt: [
    'DATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'PARTYLEDGERNAME',
    'AMOUNT',
    'LEDGERNAME',
    'ISCANCELLED',
  ],
  credit_note: [
    'DATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'PARTYLEDGERNAME',
    'PARTYGSTIN',
    'PLACEOFSUPPLY',
    'AMOUNT',
    'IRN',
    'STOCKITEMNAME',
    'BILLEDQTY',
    'RATE',
    'LEDGERNAME',
  ],
  debit_note: [
    'DATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'PARTYLEDGERNAME',
    'PARTYGSTIN',
    'PLACEOFSUPPLY',
    'AMOUNT',
    'STOCKITEMNAME',
    'BILLEDQTY',
    'RATE',
    'LEDGERNAME',
  ],
  stock_journal: [
    'DATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'STOCKITEMNAME',
    'ACTUALQTY',
    'RATE',
    'AMOUNT',
    'GODOWNNAME',
    'BATCHNAME',
  ],
  journal: [
    'DATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'LEDGERNAME',
    'AMOUNT',
    'COSTCENTRE',
  ],
  contra: [
    'DATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'LEDGERNAME',
    'AMOUNT',
  ],
  delivery_note: [
    'DATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'PARTYLEDGERNAME',
    'STOCKITEMNAME',
    'ACTUALQTY',
    'GODOWNNAME',
    'LEDGERNAME',
  ],
  receipt_note: [
    'DATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'PARTYLEDGERNAME',
    'STOCKITEMNAME',
    'ACTUALQTY',
    'GODOWNNAME',
    'LEDGERNAME',
  ],
  purchase_order: [
    'DATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'PARTYLEDGERNAME',
    'STOCKITEMNAME',
    'BILLEDQTY',
    'RATE',
    'AMOUNT',
  ],
  sales_order: [
    'DATE',
    'VOUCHERTYPENAME',
    'VOUCHERNUMBER',
    'REFERENCE',
    'NARRATION',
    'GUID',
    'MASTERID',
    'ALTERID',
    'PARTYLEDGERNAME',
    'BASICBUYERNAME',
    'PARTYGSTIN',
    'PLACEOFSUPPLY',
    'STOCKITEMNAME',
    'BILLEDQTY',
    'ACTUALQTY',
    'RATE',
    'AMOUNT',
    'LEDGERNAME',
    'GODOWNNAME',
    'ISOPTIONAL',
    'ISCANCELLED',
  ],
  unit: [
    'NAME',
    'GUID',
    'MASTERID',
    'ALTERID',
    'ORIGINALNAME',
    'ISSIMPLEUNIT',
    'DECIMALPLACES',
    'BASEUNITS',
    'ADDITIONALUNITS',
    'CONVERSION',
    'GSTREPUOM',
  ],
  currency: [
    'NAME',
    'GUID',
    'ORIGINALNAME',
    'FORMALNAME',
    'ISOCURRENCYCODE',
    'DECIMALPLACES',
    'INMILLIONS',
    'SYMBOL',
  ],
  cost_centre: ['NAME', 'PARENT', 'GUID', 'MASTERID', 'ALTERID', 'CATEGORY', 'REVENUELEDGER', 'NONREVENUELEDGER'],
  cost_category: ['NAME', 'PARENT', 'GUID', 'MASTERID', 'ALTERID'],
  voucher_type: ['NAME', 'PARENT', 'GUID', 'MASTERID', 'ALTERID'],
  price_list: ['NAME', 'GUID', 'MASTERID', 'ALTERID', 'DATE', 'RATE', 'STOCKITEMNAME', 'DISCOUNT'],
});

/** Friendly entity picker: Tally name first, then Arivu module. */
const FIELD_MAP_ENTITY_OPTIONS = Object.freeze([
  { entityType: 'party', tallyLabel: 'Ledger', arivuLabel: 'Organizations', arivuModuleKey: 'organizations' },
  { entityType: 'group', tallyLabel: 'Group', arivuLabel: 'Reference', arivuModuleKey: null },
  { entityType: 'item', tallyLabel: 'Stock Item', arivuLabel: 'Items', arivuModuleKey: 'items' },
  { entityType: 'godown', tallyLabel: 'Godown', arivuLabel: 'Inventory locations', arivuModuleKey: 'inventory_locations' },
  { entityType: 'stock_group', tallyLabel: 'Stock Group', arivuLabel: 'Catalog categories', arivuModuleKey: 'catalog_categories' },
  { entityType: 'stock_category', tallyLabel: 'Stock Category', arivuLabel: 'Catalog categories', arivuModuleKey: 'catalog_categories' },
  { entityType: 'tax_ledger', tallyLabel: 'GST / Tax Ledger', arivuLabel: 'Tax mapping', arivuModuleKey: null },
  { entityType: 'price_list', tallyLabel: 'Price Level', arivuLabel: 'Catalog price books', arivuModuleKey: null },
  { entityType: 'invoice', tallyLabel: 'Sales', arivuLabel: 'Invoices', arivuModuleKey: 'invoices' },
  { entityType: 'purchase', tallyLabel: 'Purchase', arivuLabel: 'Purchase bills', arivuModuleKey: 'purchase_bills' },
  { entityType: 'receipt', tallyLabel: 'Receipt', arivuLabel: 'Payments', arivuModuleKey: 'payments' },
  { entityType: 'payment', tallyLabel: 'Payment', arivuLabel: 'Vendor payments', arivuModuleKey: 'vendor_payments' },
  { entityType: 'credit_note', tallyLabel: 'Credit Note', arivuLabel: 'Invoices', arivuModuleKey: 'invoices' },
  { entityType: 'debit_note', tallyLabel: 'Debit Note', arivuLabel: 'Invoices', arivuModuleKey: 'invoices' },
  { entityType: 'journal', tallyLabel: 'Journal', arivuLabel: 'Journal entries', arivuModuleKey: 'journal_entries' },
  { entityType: 'contra', tallyLabel: 'Contra', arivuLabel: 'Journal entries', arivuModuleKey: 'journal_entries' },
  { entityType: 'stock_journal', tallyLabel: 'Stock Journal', arivuLabel: 'Inventory transfers', arivuModuleKey: 'inventory_transfers' },
  { entityType: 'delivery_note', tallyLabel: 'Delivery Note', arivuLabel: 'Delivery notes', arivuModuleKey: 'delivery_notes' },
  { entityType: 'receipt_note', tallyLabel: 'Receipt Note', arivuLabel: 'Receipt notes', arivuModuleKey: 'receipt_notes' },
  { entityType: 'purchase_order', tallyLabel: 'Purchase Order', arivuLabel: 'Purchase orders', arivuModuleKey: 'purchase_orders' },
  { entityType: 'sales_order', tallyLabel: 'Sales Order', arivuLabel: 'Sales orders', arivuModuleKey: 'sales_orders' },
  { entityType: 'unit', tallyLabel: 'Unit', arivuLabel: 'Reference', arivuModuleKey: null },
  { entityType: 'currency', tallyLabel: 'Currency', arivuLabel: 'Reference', arivuModuleKey: null },
  { entityType: 'cost_centre', tallyLabel: 'Cost Centre', arivuLabel: 'Reference', arivuModuleKey: null },
  { entityType: 'cost_category', tallyLabel: 'Cost Category', arivuLabel: 'Reference', arivuModuleKey: null },
  { entityType: 'voucher_type', tallyLabel: 'Voucher Type', arivuLabel: 'Reference', arivuModuleKey: null },
]);

/** Extra Arivu fields beyond module schema (variant / CRM / sync triad). */
const ARIVU_EXTRA_FIELDS = Object.freeze({
  party: [
    'name',
    'organizationNumber',
    'types',
    'website',
    'phone',
    'email',
    'address',
    'billingAddressStructured',
    'shippingAddress',
    'gstin',
    'gstRegistrationType',
    'stateCode',
    'taxId',
    'externalReferenceId',
    'syncStatus',
    'lastSyncAt',
  ],
  item: [
    'item_name',
    'item_code',
    'variant_code',
    'unit_of_measure',
    'hsnSac',
    'gstTaxability',
    'gstRatePercent',
    'selling_price',
    'cost_price',
    'barcode',
    'category',
    'categoryId',
    'externalReferenceId',
    'syncStatus',
  ],
  godown: [
    'name',
    'locationCode',
    'description',
    'locationType',
    'parentLocationId',
    'isDefault',
    'addressSnapshot',
    'externalReferenceId',
    'syncStatus',
  ],
  invoice: [
    'invoiceNumber',
    'invoiceType',
    'invoiceDate',
    'postedAt',
    'status',
    'currency',
    'subtotal',
    'taxTotal',
    'grandTotal',
    'partyGstin',
    'placeOfSupply',
    'irn',
    'ackNo',
    'ackDate',
    'ewayBillNo',
    'organizationRefId',
    'customerId',
    'externalReferenceId',
    'syncStatus',
  ],
});

module.exports = {
  TALLY_FIELD_CATALOGS,
  FIELD_MAP_ENTITY_OPTIONS,
  ARIVU_EXTRA_FIELDS,
  /**
   * ATIP 1B: prefer discovered TallyObjectSchema fields; fall back to golden fixture catalog.
   */
  async getRuntimeFieldCatalog({ organizationId, companyGuid, entityType }) {
    try {
      const metadataEngine = require('./engines/metadataEngine');
      const objectKey = String(entityType || '')
        .toLowerCase()
        .replace(/^party$/, 'ledger')
        .replace(/^item$/, 'stock_item')
        .replace(/^invoice$/, 'sales');
      const schema = await metadataEngine.getObjectSchema({
        organizationId,
        companyGuid,
        objectKey,
      });
      if (schema?.fields?.length) {
        return {
          source: 'discovered',
          fields: schema.fields.map((f) => f.name),
          schema,
        };
      }
    } catch {
      /* fall through */
    }
    const fields = TALLY_FIELD_CATALOGS[entityType] || TALLY_FIELD_CATALOGS[String(entityType).toLowerCase()] || [];
    return { source: 'fixture', fields };
  },
};
