'use strict';

const fs = require('fs');
const path = require('path');

const PATCH_MARKER = 'withArivuHelp';

function normalizePathPrefix(prefix) {
  let value = String(prefix || '/help/').trim();
  if (!value.startsWith('/')) value = `/${value}`;
  if (!value.endsWith('/')) value = `${value}/`;
  return value;
}

function buildArivuHelpConfigContent(pathPrefix) {
  const normalized = normalizePathPrefix(pathPrefix);
  const base = normalized.replace(/\/$/, '') || '/help';
  return `/**
 * Arivu help center — auto-generated by arivu-help-install
 * Merges static /help rewrites into your Next.js config.
 */
export function getArivuHelpRewrites() {
  return [
    { source: '${base}', destination: '${base}/index.html' },
    { source: '${base}/', destination: '${base}/index.html' },
    { source: '${base}/:path+/', destination: '${base}/:path+/index.html' },
    { source: '${base}/:path+', destination: '${base}/:path+/index.html' },
  ];
}

export function withArivuHelp(config = {}) {
  const existingRewrites = config.rewrites;
  return {
    ...config,
    async rewrites() {
      const arivu = getArivuHelpRewrites();
      const base = typeof existingRewrites === 'function'
        ? await existingRewrites()
        : (existingRewrites || []);
      return [...arivu, ...base];
    },
  };
}
`;
}

function patchPackageJson(packageJsonPath, options = {}) {
  const integrationMode = options.integrationMode || 'hybrid';
  const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  pkg.scripts = pkg.scripts || {};

  // static SEO + hybrid both write public/help HTML at build time
  if (integrationMode === 'standalone-html' || integrationMode === 'hybrid' || integrationMode === 'layout') {
    if (!pkg.scripts['sync:help']) {
      pkg.scripts['sync:help'] = 'node scripts/sync-help-static.mjs';
    }

    if (integrationMode !== 'layout') {
      const syncCommand = 'npm run sync:help';
      const existingPrebuild = String(pkg.scripts.prebuild || '').trim();
      if (!existingPrebuild) {
        pkg.scripts.prebuild = syncCommand;
      } else if (!existingPrebuild.includes('sync:help')) {
        pkg.scripts.prebuild = `${syncCommand} && ${existingPrebuild}`;
      }
    }
  }

  fs.writeFileSync(packageJsonPath, `${JSON.stringify(pkg, null, 2)}\n`);
  return pkg.scripts;
}

function patchNextConfig(configPath) {
  if (!configPath || !fs.existsSync(configPath)) {
    return { created: false, patched: false, skipped: true };
  }

  const original = fs.readFileSync(configPath, 'utf8');
  if (original.includes(PATCH_MARKER)) {
    return { created: false, patched: false, skipped: true };
  }

  const ext = path.extname(configPath);
  const isCjs = ext === '.js' && !original.includes('export ');
  const importLine = isCjs
    ? "const { withArivuHelp } = require('./arivu-help.config.cjs');\n"
    : "import { withArivuHelp } from './arivu-help.config.mjs';\n";

  let patched = original;

  if (/export\s+default\s+[A-Za-z_$][\w$]*\s*;?/.test(patched)) {
    patched = patched.replace(
      /export\s+default\s+([A-Za-z_$][\w$]*)\s*;?/,
      'export default withArivuHelp($1);',
    );
  } else if (/export\s+default\s+\(/.test(patched)) {
    patched = patched.replace(/export\s+default\s+/, 'export default withArivuHelp(');
    patched = `${patched.trimEnd()});\n`;
  } else if (/export\s+default\s+\{/.test(patched)) {
    patched = patched.replace(/export\s+default\s+\{/, 'export default withArivuHelp({');
    patched = patched.replace(/\}\s*;?\s*$/, '});\n');
  } else if (/module\.exports\s*=\s*[A-Za-z_$][\w$]*\s*;?/.test(patched)) {
    patched = patched.replace(
      /module\.exports\s*=\s*([A-Za-z_$][\w$]*)\s*;?/,
      'module.exports = withArivuHelp($1);',
    );
  } else if (/module\.exports\s*=\s*\{/.test(patched)) {
    patched = patched.replace(/module\.exports\s*=\s*\{/, 'module.exports = withArivuHelp({');
    patched = patched.replace(/\}\s*;?\s*$/, '});\n');
  } else {
    return { created: false, patched: false, skipped: true, reason: 'unsupported next.config shape' };
  }

  fs.writeFileSync(configPath, `${importLine}${patched}`);
  return { created: false, patched: true, skipped: false, isCjs };
}

function createDefaultNextConfig(cwd, pathPrefix) {
  const configPath = path.join(cwd, 'next.config.mjs');
  if (fs.existsSync(configPath)) {
    return { created: false, path: configPath };
  }

  const content = `import { withArivuHelp } from './arivu-help.config.mjs';

/** @type {import('next').NextConfig} */
const nextConfig = withArivuHelp({});

export default nextConfig;
`;
  fs.writeFileSync(configPath, content);
  return { created: true, path: configPath };
}

function parseEnvEntries(content) {
  const order = [];
  const values = new Map();
  for (const rawLine of String(content || '').split(/\r?\n/)) {
    const line = rawLine.trimEnd();
    if (!line || line.trimStart().startsWith('#')) continue;
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!match) continue;
    const key = match[1];
    if (!values.has(key)) order.push(key);
    values.set(key, match[2]);
  }
  return { order, values };
}

/**
 * Upsert keys into an env file without wiping unrelated entries.
 * Empty updates for preserveEmptyKeys keep any existing non-empty value (secrets, deploy hooks).
 */
function upsertEnvFile(filePath, updates, options = {}) {
  const preserveEmptyKeys = new Set(options.preserveEmptyKeys || []);
  const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
  const { order, values } = parseEnvEntries(existing);

  for (const [key, rawValue] of Object.entries(updates)) {
    const nextValue = rawValue == null ? '' : String(rawValue);
    const current = values.has(key) ? String(values.get(key) || '') : null;
    if (
      preserveEmptyKeys.has(key)
      && nextValue === ''
      && current !== null
      && current.trim() !== ''
    ) {
      continue;
    }
    if (!values.has(key)) order.push(key);
    values.set(key, nextValue);
  }

  const body = `${order.map((key) => `${key}=${values.get(key)}`).join('\n')}\n`;
  ensureDirForFile(filePath);
  fs.writeFileSync(filePath, body);
  return filePath;
}

function ensureDirForFile(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function resolveSyncMode(integrationMode) {
  if (integrationMode === 'standalone-html') return 'static';
  if (integrationMode === 'layout') return 'layout';
  return 'hybrid';
}

function writeEnvFile(cwd, values, filename) {
  const integrationMode = values.integrationMode || 'hybrid';
  const filePath = path.join(cwd, filename);
  upsertEnvFile(filePath, {
    ARIVU_HELP_ORG: values.org,
    ARIVU_API_ORIGIN: values.apiOrigin.replace(/\/$/, ''),
    HELP_URL_PREFIX: normalizePathPrefix(values.pathPrefix),
    ARIVU_SYNC_MODE: resolveSyncMode(integrationMode),
    ARIVU_SYNC_DEST: values.dest || './public',
    SITE_ORIGIN: values.siteOrigin || '',
    ARIVU_WEBHOOK_SECRET: '',
    VERCEL_DEPLOY_HOOK_URL: '',
  }, {
    preserveEmptyKeys: ['ARIVU_WEBHOOK_SECRET', 'ARIVU_BLOG_WEBHOOK_SECRET', 'VERCEL_DEPLOY_HOOK_URL'],
  });
  return filePath;
}

function writeArivuHelpConfig(cwd, pathPrefix) {
  const filePath = path.join(cwd, 'arivu-help.config.mjs');
  fs.writeFileSync(filePath, buildArivuHelpConfigContent(pathPrefix));
  return filePath;
}

module.exports = {
  PATCH_MARKER,
  normalizePathPrefix,
  buildArivuHelpConfigContent,
  patchPackageJson,
  patchNextConfig,
  createDefaultNextConfig,
  writeEnvFile,
  upsertEnvFile,
  writeArivuHelpConfig,
};
