'use strict';

/**
 * Seeded Tally ↔ Arivu module mapping table defaults.
 * Sync ways: disabled | tally_to_arivu | arivu_to_tally | bidirectional
 */

const TALLY_SYNC_WAYS = Object.freeze([
  'disabled',
  'tally_to_arivu',
  'arivu_to_tally',
  'bidirectional',
]);

/** Dependency order for low-pressure sync (masters before vouchers). */
const TALLY_MODULE_SYNC_ORDER = Object.freeze([
  'unit',
  'currency',
  'group',
  'voucher_type',
  'cost_category',
  'cost_centre',
  'tax_unit',
  'gst_classification',
  'stock_group',
  'stock_category',
  'godown',
  'batch',
  'ledger',
  'stock_item',
  'sales_order',
  'purchase_order',
  'sales',
  'purchase',
  'credit_note',
  'debit_note',
  'receipt',
  'payment',
  'journal',
  'contra',
  'stock_journal',
  'delivery_note',
  'receipt_note',
]);

const DEFAULT_MODULE_MAPPINGS = Object.freeze([
  {
    tallyModuleKey: 'ledger',
    tallyModuleName: 'Ledger (Debtors/Creditors)',
    arivuModuleKey: 'organizations',
    arivuModuleName: 'Organizations',
    entityType: 'party',
    syncWay: 'bidirectional',
    filter: {
      parents: ['Sundry Debtors', 'Sundry Creditors'],
      excludeSystemLedgers: true,
    },
    syncOrder: 13,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'stock_item',
    tallyModuleName: 'Stock Item',
    arivuModuleKey: 'items',
    arivuModuleName: 'Items',
    entityType: 'item',
    syncWay: 'bidirectional',
    filter: { requireUom: true },
    syncOrder: 14,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'stock_group',
    tallyModuleName: 'Stock Group',
    arivuModuleKey: 'catalog_categories',
    arivuModuleName: 'Catalog categories',
    entityType: 'stock_group',
    syncWay: 'bidirectional',
    filter: {},
    syncOrder: 9,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'stock_category',
    tallyModuleName: 'Stock Category',
    arivuModuleKey: 'catalog_categories',
    arivuModuleName: 'Catalog categories',
    entityType: 'stock_category',
    syncWay: 'bidirectional',
    filter: {},
    syncOrder: 10,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'godown',
    tallyModuleName: 'Godown',
    arivuModuleKey: 'inventory_locations',
    arivuModuleName: 'Inventory locations',
    entityType: 'godown',
    syncWay: 'bidirectional',
    filter: {},
    syncOrder: 11,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'unit',
    tallyModuleName: 'Unit',
    arivuModuleKey: null,
    arivuModuleName: '— (reference)',
    entityType: 'unit',
    syncWay: 'tally_to_arivu',
    filter: {},
    syncOrder: 1,
    discoverOnly: false,
    referenceOnly: true,
  },
  {
    tallyModuleKey: 'currency',
    tallyModuleName: 'Currency',
    arivuModuleKey: null,
    arivuModuleName: '— (reference)',
    entityType: 'currency',
    syncWay: 'tally_to_arivu',
    filter: {},
    syncOrder: 2,
    discoverOnly: false,
    referenceOnly: true,
  },
  {
    tallyModuleKey: 'cost_centre',
    tallyModuleName: 'Cost Centre',
    arivuModuleKey: null,
    arivuModuleName: '— (journal cache)',
    entityType: 'cost_centre',
    syncWay: 'tally_to_arivu',
    filter: {},
    syncOrder: 6,
    discoverOnly: false,
    referenceOnly: true,
  },
  {
    tallyModuleKey: 'cost_category',
    tallyModuleName: 'Cost Category',
    arivuModuleKey: null,
    arivuModuleName: '— (reference)',
    entityType: 'cost_category',
    syncWay: 'tally_to_arivu',
    filter: {},
    syncOrder: 5,
    discoverOnly: false,
    referenceOnly: true,
  },
  {
    tallyModuleKey: 'group',
    tallyModuleName: 'Group',
    arivuModuleKey: null,
    arivuModuleName: '— (reference)',
    entityType: 'group',
    syncWay: 'tally_to_arivu',
    filter: {},
    syncOrder: 3,
    discoverOnly: false,
    referenceOnly: true,
  },
  {
    tallyModuleKey: 'voucher_type',
    tallyModuleName: 'Voucher Type',
    arivuModuleKey: null,
    arivuModuleName: '— (reference)',
    entityType: 'voucher_type',
    syncWay: 'tally_to_arivu',
    filter: {},
    syncOrder: 4,
    discoverOnly: false,
    referenceOnly: true,
  },
  {
    tallyModuleKey: 'tax_unit',
    tallyModuleName: 'Tax Unit',
    arivuModuleKey: null,
    arivuModuleName: '— (reference)',
    entityType: 'tax_unit',
    syncWay: 'tally_to_arivu',
    filter: {},
    syncOrder: 7,
    discoverOnly: false,
    referenceOnly: true,
  },
  {
    tallyModuleKey: 'gst_classification',
    tallyModuleName: 'GST Classification',
    arivuModuleKey: null,
    arivuModuleName: '— (reference)',
    entityType: 'gst_classification',
    syncWay: 'tally_to_arivu',
    filter: {},
    syncOrder: 8,
    discoverOnly: false,
    referenceOnly: true,
  },
  {
    tallyModuleKey: 'batch',
    tallyModuleName: 'Batch',
    arivuModuleKey: null,
    arivuModuleName: '— (reference)',
    entityType: 'batch',
    syncWay: 'tally_to_arivu',
    filter: {},
    syncOrder: 12,
    discoverOnly: false,
    referenceOnly: true,
  },
  {
    tallyModuleKey: 'sales',
    tallyModuleName: 'Sales',
    arivuModuleKey: 'invoices',
    arivuModuleName: 'Invoices',
    entityType: 'invoice',
    syncWay: 'arivu_to_tally',
    filter: { postedOnly: true, dateWindowDays: 30 },
    syncOrder: 17,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'purchase',
    tallyModuleName: 'Purchase',
    arivuModuleKey: 'purchase_bills',
    arivuModuleName: 'Purchase bills',
    entityType: 'purchase',
    syncWay: 'arivu_to_tally',
    filter: { postedOnly: true, dateWindowDays: 30 },
    syncOrder: 18,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'receipt',
    tallyModuleName: 'Receipt',
    arivuModuleKey: 'payments',
    arivuModuleName: 'Payments',
    entityType: 'receipt',
    syncWay: 'arivu_to_tally',
    filter: { postedOnly: true, dateWindowDays: 30 },
    syncOrder: 21,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'payment',
    tallyModuleName: 'Payment',
    arivuModuleKey: 'vendor_payments',
    arivuModuleName: 'Vendor payments',
    entityType: 'payment',
    syncWay: 'arivu_to_tally',
    filter: { postedOnly: true, dateWindowDays: 30 },
    syncOrder: 22,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'credit_note',
    tallyModuleName: 'Credit Note',
    arivuModuleKey: 'invoices',
    arivuModuleName: 'Invoices (credit note)',
    entityType: 'credit_note',
    syncWay: 'arivu_to_tally',
    filter: { postedOnly: true, dateWindowDays: 30 },
    syncOrder: 19,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'debit_note',
    tallyModuleName: 'Debit Note',
    arivuModuleKey: 'invoices',
    arivuModuleName: 'Invoices (debit note)',
    entityType: 'debit_note',
    syncWay: 'arivu_to_tally',
    filter: { postedOnly: true, dateWindowDays: 30 },
    syncOrder: 20,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'journal',
    tallyModuleName: 'Journal',
    arivuModuleKey: 'journal_entries',
    arivuModuleName: 'Journal entries',
    entityType: 'journal',
    syncWay: 'arivu_to_tally',
    filter: { postedOnly: true, dateWindowDays: 30 },
    syncOrder: 23,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'contra',
    tallyModuleName: 'Contra',
    arivuModuleKey: 'journal_entries',
    arivuModuleName: 'Journal entries (contra)',
    entityType: 'contra',
    syncWay: 'arivu_to_tally',
    filter: { dateWindowDays: 30 },
    syncOrder: 24,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'stock_journal',
    tallyModuleName: 'Stock Journal',
    arivuModuleKey: 'inventory_transfers',
    arivuModuleName: 'Inventory transfers / adjustments',
    entityType: 'stock_journal',
    syncWay: 'bidirectional',
    filter: { dateWindowDays: 30 },
    syncOrder: 25,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'delivery_note',
    tallyModuleName: 'Delivery Note',
    arivuModuleKey: 'delivery_notes',
    arivuModuleName: 'Delivery notes',
    entityType: 'delivery_note',
    syncWay: 'arivu_to_tally',
    filter: { dateWindowDays: 30 },
    syncOrder: 26,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'receipt_note',
    tallyModuleName: 'Receipt Note',
    arivuModuleKey: 'receipt_notes',
    arivuModuleName: 'Receipt notes',
    entityType: 'receipt_note',
    syncWay: 'arivu_to_tally',
    filter: { dateWindowDays: 30 },
    syncOrder: 27,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'purchase_order',
    tallyModuleName: 'Purchase Order',
    arivuModuleKey: 'purchase_orders',
    arivuModuleName: 'Purchase orders',
    entityType: 'purchase_order',
    syncWay: 'arivu_to_tally',
    filter: { postedOnly: true, dateWindowDays: 90 },
    syncOrder: 16,
    discoverOnly: false,
  },
  {
    tallyModuleKey: 'sales_order',
    tallyModuleName: 'Sales Order',
    arivuModuleKey: 'sales_orders',
    arivuModuleName: 'Sales orders',
    entityType: 'sales_order',
    syncWay: 'arivu_to_tally',
    filter: { postedOnly: true, dateWindowDays: 90 },
    syncOrder: 15,
    discoverOnly: false,
  },
  // Discover-only (no Arivu module yet)
  {
    tallyModuleKey: 'employee',
    tallyModuleName: 'Employee',
    arivuModuleKey: null,
    arivuModuleName: '—',
    entityType: 'employee',
    syncWay: 'disabled',
    filter: {},
    syncOrder: 100,
    discoverOnly: true,
  },
  {
    tallyModuleKey: 'pay_head',
    tallyModuleName: 'Pay Head',
    arivuModuleKey: null,
    arivuModuleName: '—',
    entityType: 'pay_head',
    syncWay: 'disabled',
    filter: {},
    syncOrder: 101,
    discoverOnly: true,
  },
  {
    tallyModuleKey: 'attendance_type',
    tallyModuleName: 'Attendance Type',
    arivuModuleKey: null,
    arivuModuleName: '—',
    entityType: 'attendance_type',
    syncWay: 'disabled',
    filter: {},
    syncOrder: 102,
    discoverOnly: true,
  },
  {
    tallyModuleKey: 'budget',
    tallyModuleName: 'Budget',
    arivuModuleKey: null,
    arivuModuleName: '—',
    entityType: 'budget',
    syncWay: 'disabled',
    filter: {},
    syncOrder: 103,
    discoverOnly: true,
  },
  {
    tallyModuleKey: 'price_list',
    tallyModuleName: 'Price List',
    arivuModuleKey: null,
    arivuModuleName: '—',
    entityType: 'price_list',
    syncWay: 'disabled',
    filter: {},
    syncOrder: 104,
    discoverOnly: true,
  },
]);

const ARIVU_MODULE_OPTIONS = Object.freeze([
  { key: null, label: '— (none / reference)' },
  { key: 'organizations', label: 'Organizations' },
  { key: 'items', label: 'Items' },
  { key: 'catalog_categories', label: 'Catalog categories' },
  { key: 'inventory_locations', label: 'Inventory locations' },
  { key: 'invoices', label: 'Invoices' },
  { key: 'payments', label: 'Payments' },
  { key: 'purchase_bills', label: 'Purchase bills' },
  { key: 'vendor_payments', label: 'Vendor payments' },
  { key: 'purchase_orders', label: 'Purchase orders' },
  { key: 'sales_orders', label: 'Sales orders' },
  { key: 'receipt_notes', label: 'Receipt notes' },
  { key: 'delivery_notes', label: 'Delivery notes' },
  { key: 'journal_entries', label: 'Journal entries' },
  { key: 'inventory_transfers', label: 'Inventory transfers / adjustments' },
  { key: 'people', label: 'People' },
  { key: 'taxes', label: 'Taxes' },
]);

/** masterType / exportId → tallyModuleKey for inbound pulls */
const PULL_MASTER_TO_MODULE = Object.freeze({
  Ledger: 'ledger',
  GstDutyLedger: 'ledger',
  StockItem: 'stock_item',
  StockSummary: 'stock_item',
  StockGroup: 'stock_group',
  StockCategory: 'stock_category',
  Godown: 'godown',
  Unit: 'unit',
  Currency: 'currency',
  Group: 'group',
  VoucherType: 'voucher_type',
  CostCategory: 'cost_category',
  CostCentre: 'cost_centre',
  TaxUnit: 'tax_unit',
  GSTClassification: 'gst_classification',
  Batch: 'batch',
  AttendanceType: 'attendance_type',
  Voucher: 'sales',
});

module.exports = {
  TALLY_SYNC_WAYS,
  TALLY_MODULE_SYNC_ORDER,
  DEFAULT_MODULE_MAPPINGS,
  ARIVU_MODULE_OPTIONS,
  PULL_MASTER_TO_MODULE,
};
